[global]
    target = "~/bin"
    upgrade_only=true

["pkgxdev/pkgx"]
    asset_filters = ['^.asc']
["Schniz/fnm"]
["dandavison/delta"]
    asset_filters = ["x86_64-unknown-linux-musl.tar.gz"]
["watchexec/watchexec"]
    asset_filters = ['linux-musl.tar.xz', '^xz.b3', '^xz.sha512']
["multiprocessio/dsq"]
["antonmedv/fx"]
["TomWright/dasel"]
    asset_filters = ['_amd64.gz']
["devspace-sh/devspace"]
["sharkdp/bat"]
    asset_filters = ["x86_64-unknown-linux-musl.tar.gz"]
["carvel-dev/ytt"]
["denoland/deno"]
    asset_filters = ['^denort']
["sachaos/viddy"]
["cantino/mcfly"]
["junegunn/fzf"]
["ogham/exa"]
    asset_filters = ['musl']
["sharkdp/fd"]
    asset_filters = ['musl']
["BurntSushi/ripgrep"]
["derailed/k9s"]
    asset_filters = ['amd64.tar.gz', '^sbom']
["grafana/k6"]
    asset_filters = ['amd64.tar.gz']
["casey/just"]
["twpayne/chezmoi"]
    asset_filters = ['musl_amd64.tar.gz']
["zellij-org/zellij"]
["starship/starship"]
    asset_filters = ['musl.tar.gz']
["sigoden/aichat"]
["ast-grep/ast-grep"]
["charmbracelet/mods"]
    asset_filters = ['x86_64.tar.gz', '^sbom']
["charmbracelet/glow"]
    asset_filters = ["^sbom"]
# ["Canop/broot"]
    # file  = 'x86_64-unknown-linux-musl/broot'
["charmbracelet/gum"]
    asset_filters = ['x86_64.tar.gz', '^sbom']
["aaronriekenberg/rust-parallel"]
["suyashkumar/dicom"]
["prefix-dev/pixi"]
    asset_filters = ['musl.tar.gz']
["jetpack-io/devbox"]
["jdx/mise"]
    asset_filters = ['linux-x64-musl.tar.xz']
["leona/helix-gpt"]
    file = "helix-gpt-0.28-x86_64-linux"
["extrawurst/gitui"]
    asset_filters = ["linux-musl"]
["earthly/earthly"]
["Morganamilo/paru"]
    asset_filters = ["x86_64.tar.zst"]
["duckdb/duckdb"]
    asset_filters = ["duckdb_cli-linux-amd64"]
["astral-sh/uv"]
    asset_filters = ["uv-x86_64-unknown-linux-musl"]
["ankitpokhrel/jira-cli"]
["Orange-OpenSource/hurl"]
