words = [
    "Konica",
    "abcloudz",
    "abcouldz",
    "asr",
    "dicom",
    "dotenv",
    "dto",
    "eoy",
    "frontends",
    "frontent",
    "fte",
    "goml",
    "jira",
    "llm",
    "nats",
    "nestjs",
    "oru",
    "pambrun",
    "poc",
    "radiopedia",
    "spacebar",
    "sso",
    "typeorm",
    "worklist",
    "worktree",
]
