[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "python"
language-servers = [ "ruff-lsp", "pylsp" ]
formatter = {command = "sh", args = ["-c", "ruff format - | ruff check --fix-only -"] }
